name: 'fetch-captain'

description: '获取 Bilibili 大航海列表'

author: 'yjl9903'

inputs:
  ruid:
    required: true
    description: 'up 主 uid'
  roomid:
    required: true
    description: '直播房间 id'
  outDir:
    required: false
    description: '输出目录'
    default: './'
  offset:
    required: false
    description: '时间偏移量'
    default: '0'

runs:
  using: 'node20'
  main: 'dist/index.js'
