name: 'fetch-captain'
description: 'Fetch captain'
author: 'yjl9903'

inputs:
  roomid:
    required: true
    description: '直播房间id'
  ruid:
    required: true
    description: 'up主uid'
  sender:
    required: false
    description: '发信人'
  sender_host:
    required: false
    description: 'SMTP Host'
  sender_pass:
    required: false
    description: '发信人密码'
  receiver:
    required: false
    description: '收信人'

runs:
  using: 'node16'
  main: 'dist/index.js'
