name: 'fetch-captain'
description: 'Fetch captain'
author: 'yjl9903'

inputs:
  roomid:
    required: true
    description: '直播房间 id'
  ruid:
    required: true
    description: 'up 主 uid'
  outDir:
    required: false
    description: '输出目录'
    default: './'
  offset:
    required: false
    description: '时间偏移量'
    default: '0'
  sender:
    required: false
    description: '发信人'
  sender_host:
    required: false
    description: 'SMTP Host'
  sender_pass:
    required: false
    description: '发信人密码'
  receiver:
    required: false
    description: '收信人'

runs:
  using: 'node16'
  main: 'dist/index.js'
