name: 'fetch-captain'

description: '获取 Bilibili 大航海列表'

author: 'yjl9903'

inputs:
  ruid:
    required: true
    description: 'Up 主 uid'
  roomid:
    required: true
    description: '直播房间 id'
  output:
    required: false
    description: '输出 CSV 文件路径'
    default: './yyyy-MM-dd.csv'

runs:
  using: 'node20'
  main: 'dist/index.js'
